name: Kieran White
author: Kieran White
baseurl: /herring-cove
description: Portfolio / Blog
github: http://www.github.com/kieranswhite
twitter: http://www.twitter.com/kieranswhite
linkedin: http://www.linkedin.com
email: kieransw6@gmail.com      
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
